image:
  repository: REPLACED_BY_CI # CI always passes --set image.repository=<resolved dynamically>
  tag: latest # CI always passes --set image.tag=<git-sha-based tag>
replicaCount: 2
service:
  port: 80
  targetPort: 3000
ingress:
  host: taskflow.local
hpa:
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70
