apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: taskflow
spec:
  ingressClassName: traefik
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: taskflow
                port:
                  number: {{ .Values.service.port }}
