#!/usr/bin/env bash
set -uo pipefail
PROFILE=taskflow
REGION=us-east-1
ACCOUNT_ID=$(aws sts get-caller-identity --profile $PROFILE --query Account --output text 2>/dev/null)
STATE_FILTER="Name=instance-state-name,Values=running,pending,stopping,stopped"

REPORT_DIR="$(dirname "$0")/../reports"
mkdir -p "$REPORT_DIR"
REPORT_FILE="$REPORT_DIR/status-$(date +%Y%m%d-%H%M%S).md"

{
echo "# TaskFlow Status Report"
echo
echo "**Account:** $ACCOUNT_ID | **Region:** $REGION | **Generated:** $(date)"
echo

echo "## Phase 0 — Cost & Guardrails"
BUDGET=$(aws budgets describe-budget --account-id "$ACCOUNT_ID" --budget-name taskflow-total-credit --profile $PROFILE --region us-east-1 \
  --query "Budget.[BudgetLimit.Amount,CalculatedSpend.ActualSpend.Amount]" --output text 2>/dev/null)
echo "- Budget: \$$(echo "$BUDGET" | awk '{print $1}') limit, \$$(echo "$BUDGET" | awk '{print $2}') spent"
echo

echo "## Phase 1 — Network"
NAT_ID=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=taskflow-dev-nat" "$STATE_FILTER" --profile $PROFILE --region $REGION \
  --query "Reservations[].Instances[].InstanceId" --output text)
if [ "$(echo "$NAT_ID" | wc -w)" -gt 1 ]; then
  echo "- NAT instance: ⚠️ multiple matches ($NAT_ID) — stale/duplicate tag, resolve manually"
else
  NAT_STATE=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=taskflow-dev-nat" "$STATE_FILTER" --profile $PROFILE --region $REGION \
    --query "Reservations[].Instances[].State.Name" --output text)
  echo "- NAT instance: ${NAT_STATE:-none found}"
fi
echo

echo "## Phase 2 — Compute"
APP_ID=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=taskflow-dev-app-01" "$STATE_FILTER" --profile $PROFILE --region $REGION \
  --query "Reservations[].Instances[].InstanceId" --output text)
if [ "$(echo "$APP_ID" | wc -w)" -gt 1 ]; then
  echo "- App instance: ⚠️ multiple matches ($APP_ID) — stale/duplicate tag, resolve manually"
  APP_STATE=""
  SSM_STATUS=""
elif [ -z "$APP_ID" ]; then
  echo "- App instance: none found"
  APP_STATE=""
  SSM_STATUS=""
else
  APP_STATE=$(aws ec2 describe-instances --instance-ids "$APP_ID" --profile $PROFILE --region $REGION \
    --query "Reservations[].Instances[].State.Name" --output text 2>/dev/null)
  SSM_STATUS=$(aws ssm describe-instance-information --profile $PROFILE --region $REGION \
    --query "InstanceInformationList[?InstanceId=='$APP_ID'].PingStatus" --output text 2>/dev/null)
  echo "- App instance: \`$APP_ID\` — $APP_STATE"
  echo "- SSM status: $SSM_STATUS"
fi
echo

echo "## Phase 3 — Secrets"
SECRET_INFO=$(aws secretsmanager describe-secret --secret-id taskflow/dev/db-credentials --profile $PROFILE --region $REGION \
  --query "[Name,RotationEnabled]" --output text 2>/dev/null)
echo "- Secret: \`$(echo "$SECRET_INFO" | awk '{print $1}')\`, rotation enabled: $(echo "$SECRET_INFO" | awk '{print $2}')"
echo

echo "## Phase 4 — Observability"
ALARM_STATE=$(aws cloudwatch describe-alarms --alarm-names taskflow-dev-app-status-check-failed --profile $PROFILE --region $REGION \
  --query "MetricAlarms[].StateValue" --output text 2>/dev/null)
echo "- Status alarm: $ALARM_STATE"
echo

echo "## Phase 5 — Container Registry"
REPO_URI=$(aws ecr describe-repositories --repository-names taskflow-dev --profile $PROFILE --region $REGION \
  --query "repositories[].repositoryUri" --output text 2>/dev/null)
IMG_COUNT=$(aws ecr list-images --repository-name taskflow-dev --profile $PROFILE --region $REGION \
  --query "length(imageIds)" --output text 2>/dev/null)
echo "- Repo: \`$REPO_URI\`"
echo "- Images stored: $IMG_COUNT"
echo

echo "## Phase 6 — Kubernetes (k3s)"
if [ "$APP_STATE" == "running" ] && [ "$SSM_STATUS" == "Online" ]; then
  CMD_ID=$(aws ssm send-command --instance-ids "$APP_ID" --document-name "AWS-RunShellScript" \
    --parameters 'commands=["export KUBECONFIG=/etc/rancher/k3s/k3s.yaml && kubectl get pods -o wide --no-headers"]' \
    --profile $PROFILE --region $REGION --query "Command.CommandId" --output text 2>/dev/null)
  sleep 6
  PODS=$(aws ssm get-command-invocation --instance-id "$APP_ID" --command-id "$CMD_ID" --profile $PROFILE --region $REGION \
    --query "StandardOutputContent" --output text 2>/dev/null)
  echo '```'
  echo "$PODS"
  echo '```'
else
  echo "- App instance not running/online — skipped"
fi
echo

echo "## Phase 7 — CI/CD (last 3 runs)"
echo '```'
gh run list --limit 3 2>/dev/null
echo '```'
echo

echo "---"
echo "*Generated by scripts/status.sh*"
} | tee "$REPORT_FILE"

echo
echo "Report saved to: $REPORT_FILE"
